GET http://localhost:3000/week-12/part-2/api/dogs

###

GET http://localhost:3000/week-12/part-2/api/dogs/1

###

POST http://localhost:3000/week-12/part-2/api/dogs HTTP/1.1
content-type: application/json

{
    "name": "Jake",
    "age": 8
}

###

PUT http://localhost:3000/week-12/part-2/api/dogs/1 HTTP/1.1
content-type: application/json

{
    "name": "Luna the Dog",
    "age": 5
}

###

PATCH http://localhost:3000/week-12/part-2/api/dogs/1 HTTP/1.1
content-type: application/json

{
    "name": "Just Luna"
}

###

DELETE http://localhost:3000/week-12/part-2/api/dogs/1 HTTP/1.1
